### ISSUE TITLE
Balise code non lisible sur le forum

### ISSUE THREAD

**Issue by piep14** [JulienTant/laravel-france#26]
Bonjour,

on ne peut pas lire correctement le code. Voici une capture

![image](https://cloud.githubusercontent.com/assets/3505174/14882609/e1e5bc5c-0d39-11e6-94d5-872c86f329f9.png)

PS : mettre "overflow-x: auto;"  sur " .Forums__MessageList__Message__Content highlighted-code > pre

**Comment by JulienTant** [comment]
Problème réglé : https://laravel.fr/t/laravel-france/mises-a-jour-du-site?page=3#message-4745
