### ISSUE TITLE
suggestions améliorations CSS

### ISSUE THREAD

**Issue by CharlieEtienne** [JulienTant/laravel-france#32]
Je suggère d'ajouter cette règle de style : 
```css
.post>.row {
    margin-right: 0;
    margin-left: 0;
}
```
Cela aurait pour effet de corriger les deux comportements indésirables suivants : 

Pas suffisament de padding à droite sur grand écran
![2020-02-09_16h46_58](https://user-images.githubusercontent.com/9772943/74105203-028b9d00-4b5c-11ea-98a4-731c01f1457b.png)
 
Pas suffisamment de padding à gauche et à droite sur mobile
![2020-02-09_16h45_32](https://user-images.githubusercontent.com/9772943/74105212-1a632100-4b5c-11ea-86b5-be74f981a4ec.png)

**Comment by JulienTant** [comment]
C'est corrigé, merci!
